name:                haskell-classifieds-notifications
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/mckayb/haskell-classifieds-notifications#readme
license:             BSD3
author:              McKay Broderick
maintainer:          mckay.db@gmail.com
copyright:           McKay Broderick
category:            Web
extra-source-files:
- README.md

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - ApplicativeDo
  - DeriveGeneric

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wmissing-import-lists

dependencies:
  - base >= 4.7 && < 5
  - wreq
  - lens
  - text
  - bytestring
  - tagsoup
  - aeson
  - transformers
  - unordered-containers
  - sendgrid-v3
  - hashable
  - random
  - time

executables:
  haskell-classifieds-notifications:
    source-dirs:      src
    main:             Main.hs
